### ISSUE TITLE
Tutorial issues

### ISSUE THREAD

**Issue by m4t5** [ondergetekende/livescrape#2]
Hi,

Firstly, thanks for writing this, looks really useful.

I'd like to make a couple of suggestions for the tutorial page.
1. from livescrape import ScrapedPage, Css, CssMulti
   (beginner friendlify it)
2. class project_page = GithubProjectPage(ScrapedPage):
   ^^ your version didn't capitalise Page in GithubProjectPage
3. project_page = GithubProjectPage("ondergetekende", "livesscrape")
   ( double s in livesscrape)
4. print (project_page.contents) returns empty dicts. It would improve the tutorial if something came back here.

I appreciate this isn't as interesting as editing code - I'm happy to send over an error-free tutorial page (or figure out git) if it's easier.

Thanks again,

Mat

**Comment by kvdveer** [comment]
You're completely right; documentation's importance isn't quite matched by its "interestingness". I'll address these issues after my day job...

> `from livescrape import ScrapedPage, Css, CssMulti`
> (beginner friendlify it)

How would you suggest to friendlify this?

(the other points will be addressed later today)

**Comment by m4t5** [comment]
Hi Koert,

You hadn't imported anything - I think if you include the necessary imports
it'll be easier for people to get started (aka more friendly).

I'll check back when you've had a change to update it.

Thanks,

Mat

**Comment by kvdveer** [comment]
I feel that I've addressed all of the issues you mentioned, but your proofreading abilities obviously exceed mine, so could you have a look again?

Thanks for helping me out here - it's much appreciated.

**Comment by m4t5** [comment]
I just tried running it - you need to add CssLink to your imports.

The class definition also fails - I'm not sure why.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in GithubProjectPage
TypeError: **init**() takes exactly 3 arguments (2 given)

Can't do more now, will check back later.

Ta,

Mat

**Comment by m4t5** [comment]
Beautiful. To achieve perfection, lose the blank line before you define description so it can cut&paste into a console better.

Now for a look at the tutorial.

Thanks again

Mat
