### ISSUE TITLE
http headers

### ISSUE THREAD

**Issue by m4t5** [ondergetekende/livescrape#3]
Hi Koert,

I've had an unsuccessful stab at allowing one to pass user agent strings to the requests call in livescrape. Any chance you could have a look at this? I'd like to be able to instantiate livescrape with something like

page = ScrapedPage(scrape_url='zzz', headers={'User-agent':'Mozilla something or other'})

Any chance of you having a look at this?

Thanks,

Mat

**Comment by kvdveer** [comment]
I suspect you're describing a pretty common use case, I'll build support into livescrape for properly emulating a browser (user agent and cookie persistence).

In the mean time, this is the type of thing I'd implement by overriding `scrape_fetch`. The next version will also contain some example recipes on how one would do that.

**Comment by kvdveer** [comment]
I think that v0.9.4 will ease this usecase. I've uploaded it to pypi and readthedocs, although the latter is still building.

With v0.9.4, just add `scrape_headers = {'User-Agent': 'Mozilla/0.2'}` to your scraper definition.

**Comment by m4t5** [comment]
Excellent - your previous suggestion rather challenged my python skills.

Many thanks,

Mat
